# Gunakan image Node.js sebagai dasar
FROM node:16-alpine

# Set working directory di dalam kontainer
WORKDIR /app

# Salin package.json dan package-lock.json ke dalam kontainer
COPY package* .

# Install dependensi proyek
RUN npm install

# Salin seluruh proyek ke dalam kontainer
COPY . .

# Atur variabel lingkungan, gantilah 'http://example.com' dengan nilai yang sesuai
ENV NEXT_PUBLIC_API_BASE_URL=https://api.jikan.moe/v4

# Expose port 3000 (port default Next.js)
EXPOSE 3000

# Jalankan proyek saat kontainer dimulai
CMD ["npm", "run", "dev"]
